repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
        - id: check-yaml
        - id: check-json
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
        - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
        - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
        - id: mypy
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
        - id: pydocstyle
          additional_dependencies:
            - toml
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
        - id: flake8
